name: mmp_md
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - openmm>=8.0
  - openmmforcefields>=0.13   # works on Linux/macOS; ambertools available here
  - openff-toolkit>=0.15
  - openff-forcefields
  - rdkit
  - mdanalysis>=2.6
  - py3dmol
  - ipykernel
  - matplotlib
  - numpy
  - pandas
  - ffmpeg
  - pip
  - pip:
    - ipywidgets
